### ISSUE TITLE
Error: Cannot find module './local.env'

### ISSUE THREAD

**Issue by si-schweisguth** [cphyc/easy_poll#1]
Si au lancement de la commande
`node node_modules/grunt-cli/bin/grunt serve`
l'erreur suivante
`Error: Cannot find module './local.env'`
est renvoyée, alors modifier le fichier 
`easy_poll/server/config/local.ens.js` en `easy_poll/server/config/local.env.js`

**Comment by cphyc** [comment]
Bonjour,

merci pour les retours. L'erreur provenait d'une mauvaise indication dans le manuel d'installation qui est maintenant corrigée.

Bonne journée !
