### ISSUE TITLE
Répertoire manquant dist/.tmp lors de l'export des réponses aux questionnaires

### ISSUE THREAD

**Issue by si-schweisguth** [cphyc/easy_poll#3]
Lors de l'export des réponses aux questionnaires, l'erreur suivante est renvoyée : 
`{ [Error: ENOENT: no such file or directory, open '/home/tantale/easy_poll/dist/.tmp/ibv4kp8.csv']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/tantale/easy_poll/dist/.tmp/ibv4kp8.csv' }
`
Résolu en créant manuellement le répertoire .tmp (`mkdir .tmp`) dans easy_poll/dist/

**Comment by cphyc** [comment]
Merci pour le rapport d'erreur !

L'erreur est normalement corrigée pour les futures installation en faisant créer automatiquement le dossier .tmp.
